CRMApp/Models/EnquiryViewModel.cs
using System;

namespace CRMApp.Models
{
    public class EnquiryViewModel
    {
        public int Enquiry_Key { get; set; } = 0;
        public int P_Enquiry { get; set; } = 0;
        public string EnqMessage { get; set; } = "";
        public string EnqType { get; set; } = "";
        public DateTime EnqDate { get; set; }
        public string TextEnqDate { get; set; } = "";
        public int LoginCode { get; set; } = 0; // Here LoginCode=Visitors_key

        public int Visitors_Key { get; set; } = 0;
        public int P_Visitors { get; set; } = 0;
        public string VisitorName { get; set; } = "";
        public string ContactNumber { get; set; } = "";
        public string CurrentOrg { get; set; } = "";
        public int BusinessType { get; set; } = 0;
        public string TextBusinessType { get; set; } = "";
        public string Email { get; set; } = "";
    }
}

CRMApp/Controllers/CRMController.cs
using ClosedXML.Excel;
using CRMApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using Newtonsoft.Json;
using System.Collections;
using System.Data;
using System.IO.Compression;
using System.Text;

namespace CRMApp.Controllers
{
    public class CRMController : Controller
    {

        private object _SessionControl = null;
        public CustomerControl.Variables SessionControl
        {
            get
            {
                return (CustomerControl.Variables)_SessionControl;
            }
            set
            {
                _SessionControl = value;
            }
        }
        private object? _rdc = null;
        public RegisterDllClass.ValidateClass rdc
        {
            get
            {
                if (_rdc is null)
                {
                    var argSessionInstance = SessionControl;
                    _rdc = new RegisterDllClass.ValidateClass(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _rdc = (RegisterDllClass.ValidateClass)_rdc;
                }
                return (RegisterDllClass.ValidateClass)_rdc;
            }
        }
        private object? _GF1 = null;
        private GlobalFunction1.GlobalFunction1 GF1
        {
            get
            {
                if (_GF1 is null)
                {
                    var argSessionInstance = SessionControl;
                    _GF1 = new GlobalFunction1.GlobalFunction1(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _GF1 = (GlobalFunction1.GlobalFunction1)_GF1;
                }
                return (GlobalFunction1.GlobalFunction1)_GF1;
            }
        }
        private object? _df1 = null;
        private DataFunctions.DataFunctions df1
        {
            get
            {
                if (_df1 is null)
                {
                    var argSessionInstance = SessionControl;
                    _df1 = new DataFunctions.DataFunctions(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _df1 = (DataFunctions.DataFunctions)_df1;
                }
                return (DataFunctions.DataFunctions)_df1;
            }
        }
        private object? _cfc1 = null;
        private CommonFunctionsCloud.CommonFunctionsCloud cfc1
        {
            get
            {
                if (_cfc1 is null)
                {
                    var argSessionInstance = SessionControl;
                    _cfc1 = new CommonFunctionsCloud.CommonFunctionsCloud(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _cfc1 = (CommonFunctionsCloud.CommonFunctionsCloud)_cfc1;
                }
                return (CommonFunctionsCloud.CommonFunctionsCloud)_cfc1;
            }
        }
        private object? _libcustomerfeature = null;
        private CustomerFeatureLib.CustomerFeatureFunctions libcustomerfeature
        {
            get
            {
                if (_libcustomerfeature is null)
                {
                    var argSessionInstance = SessionControl;
                    _libcustomerfeature = new CustomerFeatureLib.CustomerFeatureFunctions(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _libcustomerfeature = (CustomerFeatureLib.CustomerFeatureFunctions)_libcustomerfeature;
                }
                return (CustomerFeatureLib.CustomerFeatureFunctions)_libcustomerfeature;
            }
        }
        private object? _DCLib = null;
        private DataTypeConversionLib.DataTypeConversionFunctions DCLib
        {
            get
            {
                if (_DCLib is null)
                {
                    var argSessionInstance = SessionControl;
                    _DCLib = new DataTypeConversionLib.DataTypeConversionFunctions(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _DCLib = (DataTypeConversionLib.DataTypeConversionFunctions)_DCLib;
                }
                return (DataTypeConversionLib.DataTypeConversionFunctions)_DCLib;
            }
        }
        private object? _libSaralAuth = null;
        private SaralAuthLib.LoginFunctions libSaralAuth
        {
            get
            {
                if (_libSaralAuth is null)
                {
                    var argSessionInstance = SessionControl;
                    _libSaralAuth = new SaralAuthLib.LoginFunctions(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _libSaralAuth = (SaralAuthLib.LoginFunctions)_libSaralAuth;
                }
                return (SaralAuthLib.LoginFunctions)_libSaralAuth;
            }
        }
        private object? _saleOrderLib = null;
        private SalesOrderLibrary.SalesOrderFunction saleOrderLib
        {
            get
            {
                if (_saleOrderLib is null)
                {
                    var argSessionInstance = SessionControl;
                    _saleOrderLib = new SalesOrderLibrary.SalesOrderFunction(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _saleOrderLib = (SalesOrderLibrary.SalesOrderFunction)_saleOrderLib;
                }
                return (SalesOrderLibrary.SalesOrderFunction)_saleOrderLib;
            }
        }
        private object? _libCRMTasks = null;
        private CRMTasksLibrary.CRMTasksFunction libCRMTasks
        {
            get
            {
                if (_libCRMTasks is null)
                {
                    var argSessionInstance = SessionControl;
                    _libCRMTasks = new CRMTasksLibrary.CRMTasksFunction(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _libCRMTasks = (CRMTasksLibrary.CRMTasksFunction)_libCRMTasks;
                }
                return (CRMTasksLibrary.CRMTasksFunction)_libCRMTasks;
            }
        }
        private object? _libMobileNotification = null;
        private MobileNotificationLib.MobileNotificationClass libMobileNotification
        {
            get
            {
                if (_libMobileNotification is null)
                {
                    var argSessionInstance = SessionControl;
                    _libMobileNotification = new MobileNotificationLib.MobileNotificationClass(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _libMobileNotification = (MobileNotificationLib.MobileNotificationClass)_libMobileNotification;
                }
                return (MobileNotificationLib.MobileNotificationClass)_libMobileNotification;
            }
        }
        private object? _libCalls = null;
        private CallsLibrary.CallsFunctions libCalls
        {
            get
            {
                if (_libCalls is null)
                {
                    var argSessionInstance = SessionControl;
                    _libCalls = new CallsLibrary.CallsFunctions(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _libCalls = (CallsLibrary.CallsFunctions)_libCalls;
                }
                return (CallsLibrary.CallsFunctions)_libCalls;
            }
        }
        private object? _libemployee = null;
        private EmployeeLib.EmployeeFunctions libemployee
        {
            get
            {
                if (_libemployee is null)
                {
                    var argSessionInstance = SessionControl;
                    _libemployee = new EmployeeLib.EmployeeFunctions(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _libemployee = (EmployeeLib.EmployeeFunctions)_libemployee;
                }
                return (EmployeeLib.EmployeeFunctions)_libemployee;
            }
        }
        private object? _GF2 = null;
        private GlobalFunction2.GlobalFunction2 GF2
        {
            get
            {
                if (_GF2 is null)
                {
                    var argSessionInstance = SessionControl;
                    _GF2 = new GlobalFunction2.GlobalFunction2(ref argSessionInstance);
                    SessionControl = argSessionInstance;
                    _GF2 = (GlobalFunction2.GlobalFunction2)_GF2;
                }
                return (GlobalFunction2.GlobalFunction2)_GF2;
            }
        }

        private GoggleApiFunction.Class1 gflib = new GoggleApiFunction.Class1();
        DataTable DtInfoTable = new DataTable();
        DataTable DtInfoTableuser = new DataTable();
        string authorizedMsg = "You are not authorized for this option. Please contact to system administrator.";


        public void SetSessionControl(int userloginkey_Saralweb)
        {
            SessionControl = new CustomerControl.Variables(HttpContext.Session.GetString("saraltype"), ControlTxtFile: HttpContext.Session.GetString("textcontrolfile"), encrypted: true);
            DataTable dt = df1.SqlExecuteDataTable(SessionControl.MainServerDatabase, "select userid  from userlogin where userlogin_key=" + userloginkey_Saralweb);
            if (dt.Rows.Count>0)
            {
                SessionControl = new CustomerControl.Variables(HttpContext.Session.GetString("saraltype"), mcorpid: df1.GetCellValue(dt.Rows[0], "userid").ToString()?.Trim(), ControlTxtFile: HttpContext.Session.GetString("textcontrolfile"));
                df1.SessionControl = SessionControl;
                var argSessionControl = SessionControl;
                df1.SetDbCredentials(ref argSessionControl);
                SessionControl = argSessionControl;

                var argSessionControl2 = SessionControl;
                SetSessionControlOnDLL(ref argSessionControl2);
                SessionControl = argSessionControl2;

CRMApp/Views/CRM/AddCommunication.cshtml
@{
    Layout = ""; 
}


<script src="~/Scripts/FrameWork/jquery.datetimepicker.full.min.js"></script>
<link rel="stylesheet" href="~/Content/FrameWork/jquery.datetimepicker.min.css" />
<script src="~/Scripts/Custom/AddCommunication.js"></script>

<style>
    .xdsoft_datetimepicker {
        height: 212px;
    }

    td.xdsoft_date div {
        padding: 0px 9px 0px 9px;
    }
</style>
<div class="container-fluid ">
    <div class="row">
        <div>
            <table id="example1" class="table table-bordered" cellspacing="0" style="width:100%;">
                <thead class="TableHead">
                    <tr style="text-align:center; border:1px solid #ddd; text-align:center">
                        <th style="width:2%; text-align:center; border:none">No</th>
                        <th style="width:7%; text-align:center; border:none">Remark</th>
                        <th style="width:2%; border:none; text-align:center">Date</th>
                        <th style="width:4%; border:none; text-align:center">CreatedBy</th>
                        <th style="width:9%; border:none; text-align:center">FileName</th>
                    </tr>
                </thead>
                <tbody class="TableBody" style="height:0px"></tbody>
            </table>
        </div>
        <div>
            <form Class="form-horizontal" action="@Url.Action("AddGeneralTasksRemark")" role="form" method="post" id="RegForm" enctype="multipart/form-data">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, " Check details. Please Fill Form Correctly.",new{@class = "text-danger"})
                <p class="text-center text-success">@TempData["Message"]</p>
                <br />              
                <div Class="form-group">                    
                    <Label for="inputEmail1" class="col-sm-4 control-label">Remark</Label>
                    <textarea cols="30" rows="4" name="Remark" style="width:234px"></textarea>
                </div>
                <div Class="form-group">
                    <label class="col-sm-4 control-label" style="padding-top:0px">Select Project</label>
                    <input type="file" name="file1" id="file1">
                </div>
                <div Class="text-center" style="margin:20px 0px 10px 50px">
                    <Button type="submit" Class="btn btn-primary" style="margin-right:15px">Submit</Button>
                    @*<a href="@Url.Action("ManagePendingTasks")" Class="btn btn-default">Cancel</a>*@

                    <button type="button" class="btn btn-default" data-dismiss="modal"> Cancel </button>

                </div>
            </form>
        </div>
    </div>
</div>

CRMApp/Views/CRM/AddRemarkView.cshtml
@{
    Layout = ""; 
}

@*@Optimization.Scripts.Render("~/Scripts/Add_Remark_View")*@
<script src="~/Scripts/FrameWork/jquery.datetimepicker.full.min.js"></script>
<script src="~/Scripts/Custom/AddRemarkView.js"></script>


<style>
    .xdsoft_datetimepicker {
        height: 212px;
    }

    td.xdsoft_date div {
        padding: 0px 9px 0px 9px;
    }

    div.tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }
        /* Style the buttons inside the tab */
        div.tab button {
            background-color: inherit;
            float: left;
            border: none;
            outline: none;
            cursor: pointer;
            padding: 8px 23.4px;
            transition: 0.3s;
            font-size: 15px;
        }

    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>
            <form Class="form-horizontal" action="@Url.Action("AddRemarkView")" role="form" method="post" id="RegForm" style="margin-top:0px;">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, " Check details. Please Fill Form Correctly.",new {@class = "text-danger"})          
                <p class="text-center text-success">@TempData["Message"]</p>
                @*<br />
                <div class="form-group">
                    <label class="col-sm-4 control-label" style="padding-top:0px">Defer Task</label>
                    <input type="radio" name="Defer" value="Yes" style="margin-left:10px" />Yes
                    <input type="radio" name="Defer" value="No" style="margin-left:10px" />No
                </div>
                
                <div class="form-group">
                    <label class="col-sm-4 control-label" style="padding-top:0px">Date/ Time  </label>
                    <input id="datetimepicker" name="NextActionDate"type="text" style="width:234px">
                </div>*@

                <div Class="form-group">
                    <input type="hidden" name="issueId" value="@httpContextAccessor.HttpContext?.Session.GetString("issueid")" />
                    <Label for="inputEmail1" class="col-sm-4 control-label">Remark</Label>
                    <textarea cols="30" rows="4" name="Remark"></textarea>             
                    <Button type="submit" Class="btn btn-primary" style="margin-right:15px; padding:0px; width:102px; height:26px">Submit</Button>
                    @*<a href="@Url.Action("ManageRegCalls")" Class="btn btn-default">Cancel</a>*@
                </div>
            </form>


<div class="tab" style="margin-bottom:20px">
    <button class="tablinks ShowGrid" style="padding-left:15px"> <b>Refer Previous Remarks </b></button>
</div>
<div>
    <table id="example1" class="table table-bordered" cellspacing="0" style="width:100%; height:300px; display:none">
        @*<table id="example1" class=""  style="width:100%;display:none">*@
            <thead class="TableHead">
                <tr style="text-align:center;">
                    <th style="width:2%">No</th>
                    <th style="width:12%">Remark</th>
                    <th style="width:6%">Comm. Type</th>
                    <th style="width:10%">Date</th>
                    <th style="width:7%">CreatedBy</th>
                </tr>
            </thead>
            <tbody class="TableBody"></tbody>
        </table>
</div>

CRMApp/Views/CRM/LeadForm.cshtml
@model CRMApp.Models.LeadMaster
@{
    ViewData["Title"] = "LeadForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<link rel="stylesheet" href="~/Content/bootstrap.css" />*@
<script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
@*<script src="~/Scripts/bootstrap.js" type="text/javascript"></script>*@
<link rel="stylesheet" href="~/Content/CompactForm.css" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet">
<script src="~/Scripts/DealerRegForm.js" type="text/javascript"></script>
<div Class="cont">
    <div>
        <h3 Class="text-info">Lead Form</h3>
        <hr />
        <form action="@Url.Action("LeadForm")" method="post">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, " check details. Please Fill Form Correctly.", new{@class = "text-danger"})
            @Html.HiddenFor(model=> model.Lead_Key)
            <div Class="row">
                <div Class="col-sm-6 ">
                    <div Class="form-group  form-group-sm">
                        <Label for="inputEmail" class="text-info">Topic</Label>
                        @Html.TextBoxFor(model=> model.Topic, new{@class = "form-control input-sm"})
                    </div>
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">Purchase Time</Label>
                        <select class="form-control input-sm">
                            <option selected="selected" value="- Select HomeTown -">- Select -</option>
                            <option>Allowed</option>
                            <option>Not Allowed</option>
                        </select>
                    </div>
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">Contact Name</Label>
                        @Html.List_Search("ContactCode", "- Select Contact Name -", "Contacts", "FullName", "Contact_Key","", Model.ContactCode,"" , new{@onChange = "ShowText(this.id)", @class = "form-control input-sm"})
                    </div>
                </div>
                <div Class="col-sm-6 ">
                    <div Class="form-group">
                        <Label for="inputPassword" class="text-info">Decision Maker</Label>
                        @Html.List_Search("DecisionMaker", "- Select Decision Maker Name -", "Contacts", "FullName", "Contact_Key","", Model.DecisionMaker,"", new{@onChange = "ShowText(this.id)", @class = "form-control input-sm"})
                    </div>
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">Budget</Label>
                        @Html.TextBoxFor(model=> model.Budget, new{@class = "form-control input-sm"})
                    </div>
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">Purchase Process</Label>
                        @Html.TextBoxFor(model=> model.PurchaseProcess, new{@class = "form-control input-sm"})
                    </div>
                </div>
            </div>
            <hr />
            <div Class="row">
                <div Class="col-sm-6">
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">BusinessType</Label>
                        @Html.List_Search("BussType", "F", "Select Business Type", 0,"", new{@class = "form-control input-sm"})
                    </div>
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">Daily Transaction Entry</Label>
                        @Html.TextBoxFor(model=> model.TransEntryDaily, new{@class = "form-control input-sm"})
                    </div>
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">Monthly Transaction Entry</Label>
                        @Html.TextBoxFor(model=> model.TransEntryMonthly, new{@class = "form-control input-sm"})
                    </div>
                </div>
                <div Class="col-sm-6">
                    <div Class="form-group">
                        <Label Class="text-info">Accounting Software Used</Label>
                        @Html.List_Search("BussType", "H", "Select Software",0 ,"", new{@class = "form-control input-sm"})
                    </div>
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">Daily Sales Bill</Label>
                        @Html.TextBoxFor(model=> model.SalesBillDaily, new{@class = "form-control input-sm"})
                    </div>
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">Monthly Sales Bill</Label>
                        @Html.TextBoxFor(model=> model.SalesBillMonthly, new{@class = "form-control input-sm"})
                    </div>
                </div>
            </div>
            <hr />
            <div Class="row">
                <div Class="col-sm-6">
                    <div Class="form-group">
                        <Label Class="text-info">Account Name</Label>
                        @Html.List_Search("AccountCode", "- Select Account Name -", "Accounts", "AccountName", "Account_Key", "", Model.AccountCode,"", new{@onChange = "ShowText(this.id)", @class = "form-control input-sm"})                                                                                                                           @*@Html@TextBoxFor(model=> model@SpouseName, new{@class = "form-control input-sm"})*@
                    </div>
                </div>
                <div Class="col-sm-6">
                    <div Class="form-group">
                        <Label for="inputEmail" class="text-info">Is Computer present in office</Label>
                        <div class="row input-sm">
                            <div class="col-md-6">@Html.RadioButtonFor(model=> model.ComputerYN, "1", new{@class = "form-check-input"})Yes</div>
                            <div class="col-md-6">@Html.RadioButtonFor(model=> model.ComputerYN, "0", new{@class = "form-check-input"})No</div>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div Class="row">
                <div Class="col-sm-6">
                    <div Class="form-group">
                        <Label Class="text-info">Internet Present</Label>
                        <div class="row input-sm">
                            <div class="col-md-6">@Html.RadioButtonFor(model=> model.InternetYN, "1", new{@class = "form-check-input"})Yes</div>
                            <div class="col-md-6">@Html.RadioButtonFor(model=> model.InternetYN, "0", new{@class = "form-check-input"})No</div>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div Class="text-center">
                <Button type="submit" Class="btn btn-info">Submit</Button>
                <Button type="Button" Class="btn btn-default">Cancel</Button>
            </div>
           
        </form>
    </div>
</div>

CRMApp/Views/CRM/LocationGrid.cshtml
@{
    Layout = "";
}
@*@Optimization.Scripts.Render("~/Scripts/LocationGrid")*@
<script src="~/Scripts/FrameWork/jquery.min.js"></script>
<script src="~/Scripts/FrameWork/bootstrap.js"></script>
<script src="~/Scripts/Custom/LocationGrid.js"></script>

<style>
    tr:hover td {
        background-color: lightblue;
        color: #666;
    }

    table {
        font-family: verdana,arial,sans-serif;
        font-size: 11px;
        border-collapse: collapse;
    }

    table {
        font-family: verdana,arial,sans-serif;
        font-size: 11px;
    }

    foot {
        text-align: center;
    }
</style>

<div class="col-md-12" style="padding-left:0; padding-right:0px">
    <input type="text" name="searchString" id="searchString" class="form-control input-sm col-md-6 col-sm-12" />
</div>
<input type="hidden" name="homeTown" id="homeTown" />
<div id="search" style="display:none;overflow-y:scroll; background-color:white; width:540px;height:214px; padding-left:0px" class="col-md-12">
    <table id="example" class="table nowrap" cellspacing="0" style="width:100%;">
        <thead>
            <tr style="text-align:center;">
                <th>SNo</th>
                <th>HomeTown</th>
                <th>District</th>
                <th>State</th>
                <th>Country</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

CRMApp/Views/CRM/ManageContacts.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*@Optimization.Scripts.Render("~/Scripts/Manage_Contacts")
@Optimization.Styles.Render("~/Content/Manage_Contacts")*@

<script src="~/Scripts/FrameWork/bootstrap.js"></script>
<script src="~/Scripts/Custom/ManageContacts.js"></script>

<link  rel="stylesheet" href="~/Content/FrameWork/dataTables.bootstrap.min.css"/>
<link  rel="stylesheet" href="~/Content/Custom/GridCss.css"/>
<link  rel="stylesheet" href="~/Content/Custom/ManageContacts.css"/>

<style>
    .content{
       height:580px
    }
</style>

<div class="container">
    <div class="icon-bar">
        <a class="top" title="" data-placement="bottom" data-toggle="tooltip" data-original-title="Create New" href="@Url.Action("ContactsForm", "CRM")">
            <i class="glyphicon glyphicon-plus"></i>
        </a>
        <a class="top btn-edit" title="" data-placement="bottom" data-toggle="tooltip" data-original-title="Edit" onclick="dd();">
            <i class="glyphicon glyphicon-pencil"></i>
        </a>
        <a class="top btn-delete" title="" data-placement="bottom" data-toggle="tooltip" data-original-title="Delete" onclick="dd();">
            <i class="glyphicon glyphicon-trash"></i>
        </a>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <div id="main" class="col-md-12" style="padding-right:25px">
            <div id="dropdown" class="col-md-4 search ">
                <select class="col-md-2" id="filter" style="height:26px">
                    <option value="0">Filter</option>   
                </select>
                <div id="TextC" style="display:none">
                    <input type="text" id="filterText" class="col-md-3" placeholder="Type to search" style="height:26px" /><div id="search1" onclick="DoSearch();" class="btn btn-primary"><i class="glyphicon glyphicon-search"></i></div>
                </div>
            </div>
            <div class="col-md-4" style="text-align:right; padding-right:0px; float:right">
                <label id="info"> </label>
                <div class="btn btn-default" title="" data-placement="bottom" data-toggle="tooltip" id="Prev" data-original-title="Newer" style="margin-top:10px; width:30px; padding-top:0px; padding-left:0px; padding-right:0px; padding-bottom:0px; margin-bottom:10px; color:#337ab7; border-radius:0px">
                    <i class="fa fa-angle-left" style="font-size:24px"></i>
                </div>
                <div class="btn btn-default" title="" data-placement="bottom" data-toggle="tooltip" id="Next" data-original-title="Older" style="margin-top:10px; width:30px; padding-top:0px; padding-left:0px; padding-right:0px; padding-bottom:0px; margin-bottom:10px;color:#337ab7; margin-left:0px;  border-radius:0px">
                    <i class="fa fa-angle-right" style="font-size:24px"></i>
                </div>
                <div class="btn btn-default" style="color:#337ab7; margin-left:10px; width:30px; height:25px; padding-top:0px; padding-left:0px; padding-right:0px; padding-bottom:0px; margin-bottom:10px; border-radius:0px; margin-top:10px">
                    <p id="popover1" data-placement="bottom" style="margin-top:0px;"><i class="fa fa-gear xx" style="font-size:20px; margin-top:2px"></i></p>
                    <div id="popover_content_wrapper1" style="display: none">
                        <ul style="list-style:none; padding-left:0px">
                            <li id="popover2" data-placement="left" style="left:-90px; width:90px;">Set Page Size</li>
                        </ul>
                    </div>
                    <div id="popover_content_wrapper2" style="display:none; width:148px">
                        <input type="number" id="size" style="padding:2px 2px 3px 5px; width:70%;height:25px" /><div id="pageS" onclick="PageSize();" class="btn btn-primary" style="width:23px;border-radius:0px; padding-left:3px; padding-top:3px; padding-bottom:0px; padding-right:6px ;margin-top:0px;margin-bottom: 2px;"> <i class="glyphicon glyphicon-ok"></i></div>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
</div>

<div>
    <input type="hidden" name="grid1" id="grid1" value="">
    <div class="col-md-12">      
        <table id="example" class="table row-border table-responsive" cellspacing="0">
            <thead>
                <tr style="text-align:center;">
                    <th>Select</th>
                    <th style="cursor: pointer;"><input type="hidden" id="head1" value="2:Fullname:none" />Name<i class="glyphicon glyphicon-sort sortable " id="sort-2" style="color:#C7C7C7"></i></th>
                    <th>Phone</th>
                    <th style="cursor: pointer;"><input type="hidden" id="head2" value="4:Email:none" />Email<i class="glyphicon glyphicon-sort sortable " id="sort-4" style="color:#C7C7C7"></i></th>
                    <th>Job Title</th>
                </tr>
                <tr id="loading"><td colspan="5"><div id="loadingmessage" class="loader overlay col-md-offset-6"></div><p id="Msg"></p></td></tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
<input type="hidden" id="type2" value="@ViewBag.Message" /> 